Errno exception handling
sensu-plugins/sensu-plugins-filesystem-checks pull request #15
Opened 2016-08-15 07:42 UTC by jaykumar-jnpr

#### Proposed solution to following 

[sensu-plugins-filesystem-checks/issues/14](https://github.com/sensu-plugins/sensu-plugins-filesystem-checks/issues/14)

#### Purpose

Adds few Errno exception handling to **check-fs-writable** check

- Refer [errno-exceptions](http://blog.honeybadger.io/understanding-rubys-strange-errno-exceptions/) for more details on Errno types

- Errno types included in this pull request are only specific to what errors the check might encounter. Other/out-of-ordinary exceptions remains untouched.

#### Known Compatablity Issues

None I am aware of.

2016-08-25 09:27 UTC, sstarcher commented
can you fix the travis-ci failures

2017-06-24 22:39 UTC, majormoses requested changes

2017-06-24 22:39 UTC, majormoses commented on bin/check-fs-writable.rb
> +  exit -1
I dont think we should exit with `-1` if anything it should be a 1 but anyways I also feel like this should be either an `unknown`, `warning`, or `critical` which also would remove needing to specifically redirect the output to stderr.

2017-06-24 22:39 UTC, majormoses commented on bin/check-fs-writable.rb
> +  $stderr.puts "Caught the exception: #{e}"
see comment below, anyways whatever goes here should be indented properly.

2017-07-09 16:41 UTC, majormoses commented
@jaykumar-jnpr are you planning on seeing this through to completion?

2017-07-20 01:24 UTC, majormoses commented
closing due to inactivity

2017-07-20 01:24 UTC, closed without merging